version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "automated pr"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      npm-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
